name: Java Knowledge Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MILVUS_HOST: localhost
  MILVUS_PORT: 19530
  FLASK_ENV: development

jobs:
  service-validation:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.18
        ports:
          - 2379:2379
        options: >-
          --health-cmd "etcdctl endpoint health"
          --health-interval 30s

      minio:
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"

      milvus:
        image: milvusdb/milvus:v2.5.5
        ports:
          - 19530:19530
          - 9091:9091
        env:
          ETCD_ENDPOINTS: etcd:2379
          MINIO_ADDRESS: minio:9000
        options: >-
          --health-cmd "curl -f http://localhost:9091/healthz"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Milvus connection
      run: |
        echo "等待Milvus启动..."
        timeout 120 bash -c 'until curl -s http://localhost:9091/healthz | grep "OK"; do
          sleep 10
        done'
        echo "Milvus已就绪！"

    - name: Run main application
      run: |
        echo "启动主程序..."
        python main.py --validate-only
      timeout-minutes: 5