name: Java Knowledge Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # 云端Milvus配置（通过Secrets注入）
  MILVUS_CLOUD_URI: ${{ secrets.MILVUS_URL}}  # 格式: https://xxx.api.milvus.cloud
  MILVUS_CLOUD_TOKEN: ${{ secrets.MILVUS_TOKEN }}

jobs:
  service-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Milvus connection
      run: |
        python -c "
        import os, pymilvus
        from pymilvus import connections, utility
        connections.connect(
            uri=os.getenv('MILVUS_CLOUD_URI'),
            token=os.getenv('MILVUS_CLOUD_TOKEN')
        )
        print('✅ Milvus版本:', utility.get_server_version())
        "

    - name: Run main application
      run: python main.py --validate-only
      timeout-minutes: 5